// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG0G83GcupziE3zJBiYGQhiep24KqO2Rg',
    appId: '1:313351955007:web:789634551c0a4d62a1ce8a',
    messagingSenderId: '313351955007',
    projectId: 'carshop-b54e5',
    authDomain: 'carshop-b54e5.firebaseapp.com',
    storageBucket: 'carshop-b54e5.appspot.com',
    measurementId: 'G-77Y7E7WH95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC245h9N_0g2-Rf5xyog1q4rJuXOCRtZk0',
    appId: '1:313351955007:android:e8470ed572fa93bfa1ce8a',
    messagingSenderId: '313351955007',
    projectId: 'carshop-b54e5',
    storageBucket: 'carshop-b54e5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG0G83GcupziE3zJBiYGQhiep24KqO2Rg',
    appId: '1:313351955007:web:9b9a9c5d298997e2a1ce8a',
    messagingSenderId: '313351955007',
    projectId: 'carshop-b54e5',
    authDomain: 'carshop-b54e5.firebaseapp.com',
    storageBucket: 'carshop-b54e5.appspot.com',
    measurementId: 'G-K3T8BFN897',
  );
}
